import { ToolWithRelations, Category } from '@/types/tool';

const now = new Date();
const d = (daysAgo: number) => new Date(now.getTime() - daysAgo * 86_400_000);

export const mockCategories: Category[] = [
  {
    id: 'mock-cat-1',
    name: 'LLMs & Chatbots',
    slug: 'llms-chatbots',
    description: 'Large language models and conversational AI tools.',
    icon: null,
    createdAt: d(30),
    updatedAt: d(1),
  },
  {
    id: 'mock-cat-2',
    name: 'Code Assistants',
    slug: 'code-assistants',
    description: 'AI-powered tools to help write, review, and debug code.',
    icon: null,
    createdAt: d(30),
    updatedAt: d(1),
  },
  {
    id: 'mock-cat-3',
    name: 'Image Generation',
    slug: 'image-generation',
    description: 'Generate and edit images with AI.',
    icon: null,
    createdAt: d(30),
    updatedAt: d(1),
  },
];

export const mockTools: ToolWithRelations[] = [
  {
    id: 'mock-tool-1',
    title: 'OpenHermes 2.5 — Fine-tuned Mistral 7B',
    slug: 'openhermes-25-fine-tuned-mistral-7b',
    description:
      'OpenHermes 2.5 is a fine-tuned Mistral 7B model trained on a large dataset of synthetic GPT-4 conversations. It performs surprisingly well on coding, reasoning, and instruction-following tasks.',
    url: 'https://github.com/teknium1/OpenHermes-2.5',
    imageUrl: null,
    sourceType: 'GITHUB',
    sourceId: 'mock-gh-1',
    author: 'teknium1',
    stars: 4200,
    upvotes: null,
    publishedAt: d(2),
    collectedAt: d(1),
    updatedAt: d(1),
    categoryId: 'mock-cat-1',
    category: mockCategories[0],
    tags: [],
  },
  {
    id: 'mock-tool-2',
    title: 'Continue — Open-Source AI Code Assistant',
    slug: 'continue-open-source-ai-code-assistant',
    description:
      'Continue is an open-source autopilot for VS Code and JetBrains. Connect any LLM to your IDE for code completions, chat, and inline edits without leaving your editor.',
    url: 'https://github.com/continuedev/continue',
    imageUrl: null,
    sourceType: 'GITHUB',
    sourceId: 'mock-gh-2',
    author: 'continuedev',
    stars: 11800,
    upvotes: null,
    publishedAt: d(3),
    collectedAt: d(2),
    updatedAt: d(2),
    categoryId: 'mock-cat-2',
    category: mockCategories[1],
    tags: [],
  },
  {
    id: 'mock-tool-3',
    title: 'Stable Diffusion 3.5 Large Released',
    slug: 'stable-diffusion-35-large-released',
    description:
      'Stability AI releases SD 3.5 Large with improved prompt adherence, better typography, and more consistent anatomy. Weights available on Hugging Face under a permissive non-commercial license.',
    url: 'https://www.reddit.com/r/StableDiffusion/comments/example',
    imageUrl: null,
    sourceType: 'REDDIT',
    sourceId: 'mock-rd-1',
    author: 'stability_ai',
    stars: null,
    upvotes: 3400,
    publishedAt: d(4),
    collectedAt: d(3),
    updatedAt: d(3),
    categoryId: 'mock-cat-3',
    category: mockCategories[2],
    tags: [],
  },
  {
    id: 'mock-tool-4',
    title: 'Building a Local RAG Pipeline with Ollama',
    slug: 'building-a-local-rag-pipeline-with-ollama',
    description:
      'A step-by-step guide to building a fully local retrieval-augmented generation pipeline using Ollama, LangChain, and ChromaDB. No API keys required.',
    url: 'https://medium.com/example/local-rag-ollama',
    imageUrl: null,
    sourceType: 'MEDIUM',
    sourceId: 'mock-md-1',
    author: 'Sarah Chen',
    stars: null,
    upvotes: null,
    publishedAt: d(5),
    collectedAt: d(4),
    updatedAt: d(4),
    categoryId: 'mock-cat-1',
    category: mockCategories[0],
    tags: [],
  },
  {
    id: 'mock-tool-5',
    title: 'Cursor — The AI-First Code Editor',
    slug: 'cursor-the-ai-first-code-editor',
    description:
      'Cursor is a fork of VS Code with deep AI integration. Features multi-file editing, codebase-aware chat, and inline diffs powered by GPT-4 and Claude.',
    url: 'https://www.producthunt.com/posts/cursor',
    imageUrl: null,
    sourceType: 'PRODUCTHUNT',
    sourceId: 'mock-ph-1',
    author: 'Cursor Team',
    stars: null,
    upvotes: 1870,
    publishedAt: d(6),
    collectedAt: d(5),
    updatedAt: d(5),
    categoryId: 'mock-cat-2',
    category: mockCategories[1],
    tags: [],
  },
  {
    id: 'mock-tool-6',
    title: 'Ask HN: What local LLM setup are you using in 2025?',
    slug: 'ask-hn-what-local-llm-setup-are-you-using-in-2025',
    description:
      'A popular Hacker News thread discussing local LLM setups: Ollama, LM Studio, llama.cpp, and more. Community shares hardware configs and favorite models.',
    url: 'https://news.ycombinator.com/item?id=mock123',
    imageUrl: null,
    sourceType: 'HACKERNEWS',
    sourceId: 'mock-hn-1',
    author: 'throwaway_llm',
    stars: null,
    upvotes: 620,
    publishedAt: d(7),
    collectedAt: d(6),
    updatedAt: d(6),
    categoryId: 'mock-cat-1',
    category: mockCategories[0],
    tags: [],
  },
];
